spring:
  application:
    name: auth-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

jwt:
  private-key-path: "classpath:jwtKeys/private_key.pem"
  public-key-path: "classpath:jwtKeys/public_key.pem"
  expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  refresh:
    cookie:
      name: "refresh-token"
      max-age: ${JWT_REFRESH_COOKIE_MAX_AGE:86400}